name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Nuget restore
      run: nuget restore BusyLight.sln

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Tests
      run: msbuild BusyLight.Specs\BusyLight.Specs.csproj /p:Configuration=Release
      
    - name: Setup Test Runner
      uses: Malcolmnixon/Setup-VSTest@v4

    - name: Run Tests
      run: vstest.console BusyLight.Specs\bin\Release\BusyLight.Specs.dll
